// SPDX-License-Identifier: MIT OR Apache-2.0

// Generated by scripts/sync-frontend-palette.mjs from palette.json.

export const frontendPalette = {
  "prompt": "#2df3ff",
  "local": "#ffc247",
  "patch": "#c86bff",
  "browser": "#39ff95",
  "web": "#4d8dff",
  "coordination": "#ff58d2",
  "tool": "#9fb6c3",
  "assistant": "#f8fbff",
  "message": "#f8fbff",
  "error": "#ff4761",
  "long": "#ff7a1a",
  "file": "#b7ff3d",
  "diff": "#00c2a8",
  "artifact": "#8a3dff",
  "compaction": "#ff9eea",
  "skill": "#faff00",
  "subagent": "#b084ff",
  "subagent-result": "#e2c6ff",
  "file-add": "#b7ff3d",
  "file-update": "#00c2a8",
  "file-delete": "#ff4761",
  "file-move": "#ff7a1a",
} as const;

export type PaletteKey = keyof typeof frontendPalette;

export const kindColor: Record<string, number> = {
  "prompt": 0x2df3ff,
  "local": 0xffc247,
  "patch": 0xc86bff,
  "browser": 0x39ff95,
  "web": 0x4d8dff,
  "coordination": 0xff58d2,
  "tool": 0x9fb6c3,
  "assistant": 0xf8fbff,
  "message": 0xf8fbff,
  "error": 0xff4761,
  "long": 0xff7a1a,
  "file": 0xb7ff3d,
  "diff": 0x00c2a8,
  "artifact": 0x8a3dff,
  "compaction": 0xff9eea,
  "skill": 0xfaff00,
  "subagent": 0xb084ff,
  "subagent-result": 0xe2c6ff,
  "file-add": 0xb7ff3d,
  "file-update": 0x00c2a8,
  "file-delete": 0xff4761,
  "file-move": 0xff7a1a,
};
